### ISSUE TITLE
Light Sources should be able to have different shapes

### ISSUE THREAD

**Issue by F0lak** [F0lak/Hazordhu#69]
Currently all light sources are circles.  They should be able to have different shapes, namely for cave exits, which should cast a cone shape of light in whichever direction they are meant to be facing.  This would also potentially be useful for some effects in the future.

**Comment by Kaiochao** [comment]
Should be a matter of using a different light obj with a different icon. The current spotlight's icon is generated at runtime. A cone could also be generated using slightly different math. 
Might also be able to rip generated lights from Unity's built-in lights... our lights are just white on black.
